routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//$2y$10$slYJhSHKIuo0dMbnSQ8HwOxXa9gpGda69ryHtorvl36/knIu9flwK
/*
Route::get('/',function ()
{
	return Hash::make(111);
});

Route::get('test',function ()
{
	return \Auth::id();
	//view('test');
});

//$2y$10$XUgBekTpGMnEEPhSDeSvZewyfPlfn0Oeq7NQk6joVkUv1iY1XiDm.
*/
Route::get('/','QuestionsController@index');

Auth::routes();

Route::get('/home', 'QuestionsController@index')->name('home');

Auth::routes();

Route::get('/home', 'QuestionsController@index')->name('home');

Auth::routes();

Route::resource('questions', 'QuestionsController')->except('show');
Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show');
Route::resource('questions.answers', 'AnswersController')->except(['create','show']);
Route::post('/answers/{answer}/accept','AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favorite','FavoriteQuestionController@store')->name('answers.favorite');
Route::delete('/questions/{question}/favorite','FavoriteQuestionController@destroy')->name('answers.unfavorite');

Route::post('/questions/{question}/vote','VoteQuestionController');
Route::post('/answers/{answer}/vote','VoteAnswerController');

app/Answer.php
<?php

namespace App;
use App\User;
use App\Question;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use Votabletrait, BodyTrait;
    protected $fillable=['body','user_id'];

    protected $appends=['created_date','body_html','is_best'];

    public function question()
    {
    	return $this->belongsTo(Question::class);
    }

    public function user()
    {
    	return $this->belongsTo(User::class);
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getBodyHtmlAttribute()
    {
        return  parsedown($this->body);
    }
    protected static function boot()
    {
        parent::boot();

        static::created(function($answer)
        {
            $answer->question->increment('answers_count');
        });

        static::deleted(function($answer)
        {
            $question=$answer->question;
            $question->decrement('answers_count');
            if($question->best_answer_id==$answer->id){
                $question->best_answer_id=null;
                $question->save();
            }
        });
    }

    public function getStatusAttribute()
    {
        return $this->isBest() ?"accept":"";
    }

    public function getIsBestAttribute()
    {
        return $this->isBest();
    }

    public function isBest()
    {
       return $this->id==$this->question->best_answer_id;
    }

     public function getIsvoteAttribute()
    {
       return $this->isvote();
    }
  
}

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Question;
use Illuminate\Http\Request;

class AnswersController extends Controller
{
    public function __construct()
    {
       $this->middleware('auth')->except('index');
    }
    public function index(Question $question)
    {
        return $question->answers()->with('user')->simplePaginate(3);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Question $question,Request $request)
    {        
        $question->answers()->create($request->validate(['body'=>'required'])+['user_id'=>\Auth::user()->id]);
        return back()->with('success','Your answer has been added');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question,Answer $answer)
    {
        $this->authorize('update',$answer);
        return view('answers.edit',compact('question','answer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Question $question, Answer $answer)
    {
        $this->authorize('update',$answer);
        $answer->update($request->validate(['body'=>'required']));
        if(request()->expectsJson()){
            return response()->json([
                'message'=>'Your answer has been updated',
                'body_html'=>$answer->body_html
            ],200);    
        }
        return redirect()->route('questions.show',$question->slug)->with('success','Your answer has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question,Answer $answer)
    {
        $this->authorize('delete',$answer);
        $answer->delete();
        if(request()->expectsJson()){
            return response()->json([
                'message'=>'Your answer has been deleted'
            ],200);
        }
        return redirect()->route('questions.show',$question->slug)->with('success','Your answer has been deleted');
    }
}

resources/views/answers/_answer.blade.php
<answer :answer="{{$answer}}" inline-template v-cloak>
    <div class="media split">
        <vote name="answer" :model="{{$answer}}"></vote> 
        <div class="media-body pt-2 leftBorder">
            <form v-if="editing" class="form-group" @submit.prevent="upadte">
                <textarea name="body" v-model="body" class="form-control mb-2" rows="10"></textarea>
                <div class="float-right">
                  <button  class="btn btn-outline-primary btn-sm" :disabled="isValid">Save</button>
                  <button @click="cancel" type="button" class="btn btn-outline-danger btn-sm">Cancel</button>
                </div>
            </form>
            <div v-else>
                <div v-html="bodyHtml"></div>
                <div class="row">
                    <div class="col-md-4">
                        @can('update-question',$answer)
                            <a @click="edit" class="btn btn-outline-info btn-sm">Edit</a>
                        @endcan
                
                        @can('delete-question',$answer)
                        <button type="submit" class="btn btn-sm btn-outline-danger" @click="destroy">Delete</button>
                        @endcan
                    </div>
                    
                    <div class="col-md-4"></div>
                    <div class="col-md-4 float-right">
                        @include('shared._author',[
                            'model'=>$answer,
                            'label'=>'Answered',
                        ])
                    </div>
                </div>            
            </div>
        </div>
    </div>
</answer>

resources/views/answers/_createAnswer.blade.php
    <div class="row justify-content-center">
        <div class="col-md-12">
                    <div class="card-title">
                    	<div class="d-flex align-item-center">
                    		<h4>Create Answer</h4>
                    	</div>
                        
                    </div>
                   <form method="POST" action="{{route('questions.answers.store',[$question->id])}}">
                    @csrf
                       <div class="form-group">
                            <textarea type="text" name="body" class="form-control {{$errors->has('body')?'is-invalid':''}}"  rows="10">{{old('body')}}</textarea>
                               @if($errors->has('body'))
                                   <div class="invalid-feedback">
                                        <strong>{{$errors->first('body')}}</strong>
                                    </div>
                                @endif
                        </div>
                        <div class="form-group">
                            <button class="btn btn-outline-primary byn-lg">Save answer</button>
                        </div>
                   </form>
        </div>
    </div>

resources/views/answers/_index.blade.php
   <div class="row mt-4 ">
        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-body">
                    @if($answerCount==0)
                        @if(!Auth::check())
                           Login in then add on <a href="{{route('login')}}">Click Here</a> 
                        @else
                           <strong>No answers available ... add one</strong>
                        @endif
                    @else
                     <div class="card-title ">
                        <h4>{{$answerCount}} {{Str::plural('answer',$question->answers_count)}}</h4>
                    </div>
                    <hr>
                     @include('layouts._messages')
                        @foreach($answers as $answer)
                            @include('answers._answer',['answer'=>$answer])
                        @endforeach
                    @endif
                </div>
            </div>
            @if(Auth::check())
                <div class="card">
                    <div class="card-body">
                       @include('answers._createAnswer')
                   </div>
                </div>
            @endif
            </div>
    </div>

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                	<div class="d-flex align-item-center">
                		<h2>Edite Answer for question : {{$question->title}}</h2>
                		<div class="ml-auto">
                			<a href="{{route('questions.show',$question->slug)}}" class="btn btn-outline-secondary">Back to Question</a>
                		</div>
                	</div>
                </div>
                <div class="card-body">
                   <form method="POST" action="{{route('questions.answers.update',[$question->id,$answer->id])}}">
                    @csrf
                    {{method_field('Put')}}
                    <div class="form-group">
                        <textarea type="text" name="body" id="answer-body" class="form-control {{$errors->has('body')?'is-invalid':''}}" rows="10">{{old('body',$answer->body)}}
                        </textarea>
                       @if($errors->has('body'))
                           <div class="invalid-feedback">
                                <strong>{{$errors->first('body')}}</strong>
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                            <button class="btn btn-outline-primary byn-lg">Save answer</button>
                   </div>
                   </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection