routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//$2y$10$slYJhSHKIuo0dMbnSQ8HwOxXa9gpGda69ryHtorvl36/knIu9flwK
/*
Route::get('/',function ()
{
	return Hash::make(111);
});

Route::get('test',function ()
{
	return \Auth::id();
	//view('test');
});

//$2y$10$XUgBekTpGMnEEPhSDeSvZewyfPlfn0Oeq7NQk6joVkUv1iY1XiDm.
*/
Route::get('/','QuestionsController@index');

Auth::routes();

Route::get('/home', 'QuestionsController@index')->name('home');

Auth::routes();

Route::get('/home', 'QuestionsController@index')->name('home');

Auth::routes();

Route::resource('questions', 'QuestionsController')->except('show');
Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show');
Route::resource('questions.answers', 'AnswersController')->except(['create','show']);
Route::post('/answers/{answer}/accept','AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favorite','FavoriteQuestionController@store')->name('answers.favorite');
Route::delete('/questions/{question}/favorite','FavoriteQuestionController@destroy')->name('answers.unfavorite');

Route::post('/questions/{question}/vote','VoteQuestionController');
Route::post('/answers/{answer}/vote','VoteAnswerController');

app/Question.php
<?php

namespace App;
use App\User;
use App\Answer;
use Illuminate\Support\Str;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use Votabletrait, BodyTrait;
    protected $fillable=['title','body'];

    protected $appends=['created_date','url','is_favorited','favorutes_count'];
	
	public function user()
	{
		return $this->belongsto(User::class);
	}
	public function setTitleAttribute($value)
	{
		$this->attributes['title']=$value;
		$this->attributes['slug']=Str::slug($value);
	}
	public function getUrlAttribute()
	{
		return route('questions.show',$this->slug);
	}
	public function getCreatedDateAttribute()
	{
		return $this->created_at->diffForHumans();
	}
	public function getStatusAttribute()
	{
		if($this->answers_count>0){
           if ($this->best_answer_id) {
           	 return 'accepted';
           }
           return 'answered';
		}
		return 'unanwered';
	}
	public function getBodyHtmlAttribute()
	{
		return  $this->bodyHtml();
	}
	
    public function answers()
    {
        return $this->hasMany(Answer::class)->orderBy('votes_count','DESC');
    }
    
    public function acceptBestAnswer(Answer $answer)
    {
    	$this->best_answer_id=$answer->id;
    	$this->save();
    }

    public function favorites()
    {
    	return $this->belongsToMany(User::class,'favorites')->withTimestamps();
    }

    public function isFavorited()
    {
   	    return $this->favorites()->where('user_id',\Auth::id())->count()>0;
    }

    public function getIsFavoritedAttribute()
    {
    	return $this->isFavorited();
    }

    public function getFavorutesCountAttribute()
    {
    	return $this->favorites->count();
    }

  /*  public function getExcerptAttribute()
    {
        return $this->excerpt(350);
    }

    public function excerpt($value)
    {
        return str_limit(strip_tags($this->bodyHtml()),$value);
    }

    private function bodyHtml()
    {
        return parsedown($this->body);
    }*/
    
    public function getIsvoteAttribute()
    {
       return $this->isvote();
    }
 //    public function getVotableDownAttribute()
   // {
     //   return $this->voteDown()?"vote-down":"";;
   // }

}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Http\Requests\AskQuestionRequest;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;

class QuestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions=Question::with('user')->latest()->paginate(5);
        return view('questions.index',compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $question=new Question();
        return view('questions.create',compact('question'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AskQuestionRequest $request)
    {
       $request->user()->questions()->create($request->only('title','body'));
       return redirect()->route('questions.index')->with('success','Your question is added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        $question->increment('views');

        return view('questions.show',compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        if (Gate::denies('update-question', $question)) {
            abort(403,"Access denies ...");
        }
        return view('questions.edit',compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(AskQuestionRequest $request, Question $question)
    {
        if (Gate::denies('update-question', $question)) {
            abort(403,"Access denies ...");
        }
        $question->update($request->only('title','body'));
        return redirect('/questions')->with('success','Your question is updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        if (Gate::denies('delete-question', $question)) {
            abort(403,"Access denies ...");
        }
        $question->delete();
        return redirect('/questions')->with('success','Your question is deleted successfully');
    }
}

resources/views/questions/_form.blade.php
 @csrf
<div class="form-group">
    <label class="label-control lead" for="question-title">
        Question Title
    </label>
    <input type="text" name="title" id="question-title" class="form-control {{$errors->has('title')?'is-invalid':''}}" value="{{old('title',$question->title)}}">
        @if($errors->has('title'))
            <div class="invalid-feedback">
                <strong>{{$errors->first('title')}}</strong>
            </div>
        @endif
</div>
<div class="form-group">
    <label class="label-control lead" for="question-body">
        Question Body
    </label>
    <textarea type="text" name="body" id="question-body" class="form-control {{$errors->has('body')?'is-invalid':''}}" rows="10">{{old('body',$question->body)}}</textarea>
       @if($errors->has('body'))
           <div class="invalid-feedback">
                <strong>{{$errors->first('body')}}</strong>
            </div>
        @endif
</div>
<div class="form-group">
    <button class="btn btn-outline-primary byn-lg">{{$buttonText}}</button>
</div>

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                	<div class="d-flex align-item-center">
                		<h2>Create Question</h2>
                		<div class="ml-auto">
                			<a href="{{route('questions.index')}}" class="btn btn-outline-secondary">Back to Questions</a>
                		</div>
                	</div>              
                </div>
                <div class="card-body">
                   <form method="POST" action="{{route('questions.store')}}">
                    @include('questions._form',['buttonText'=>'Ask Question'])
                   </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                	<div class="d-flex align-item-center">
                		<h2>Edite Question</h2>
                		<div class="ml-auto">
                			<a href="{{route('questions.index')}}" class="btn btn-outline-secondary">Back to Questions</a>
                		</div>
                	</div>
                </div>
                <div class="card-body">
                   <form method="POST" action="{{route('questions.update',$question->id)}}">
                    {{method_field('Put')}}
                    @include('questions._form',['buttonText'=>'Update Question'])
                   </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                	<div class="d-flex align-item-center">
                		<h2>All Questions</h2>
                        @if(Auth::check())
                		<div class="ml-auto">
                			<a href="{{route('questions.create')}}" class="btn btn-outline-secondary">Create Question</a>
                		</div>
                        @endif
                	</div>
                </div>
                <div class="card-body">
                    @include('layouts._messages')
                    @if(empty($questions))
                    <strong>
                        No questions available ...
                    </strong>
                    @else
                    	@foreach($questions as $question)
                    		<div  class="media split">
                    			<div class="counters d-flex flex-column">
                    				<div class="vote">
                    					<strong>{{$question->votes_count}}</strong>{{Str::plural('votes', $question->votes_count)}}
                    				</div>
                    				<div class="status {{$question->status}}">
                    					<strong>{{$question->answers_count}}</strong>{{Str::plural('answer', $question->answers_count)}}
                    				</div>
                    				<div class="view">
                    					{{$question->views." ".Str::plural('view', $question->views)}}
                    				</div>
                    			</div>
                    			<div class="media-body leftBorder">
                                    <div class="d-flex align-item-center">
                                        <h3 class="mt-0"><a href="{{$question->url}}">{{$question->title}}</h3></a>
                                        <div class="ml-auto">
                                            @can('update-question',$question)
                                            <a href="{{route('questions.edit',$question->id)}}" class="btn btn-outline-info btn-sm">Edit</a>
                                            @endcan
                                            @can('delete-question',$question)
                                            <form action="{{route('questions.destroy',$question->id)}}" method="post" class="formDelete">
                                                @method('Delete')
                                                @csrf
                                                <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are You Sure?')">Delete</button>
                                            </form>
                                            @endcan
                                        </div>
                                    </div>
    								<p class="lead">
    									Asked By 
    									<a href="{{$question->user->url}}">{{$question->user->name}}</a>
    									<small class="text-muted">{{$question->created_date}}</small>
    								</p>
    								{{$question->excerpt}}
    							</div>
    						</div>
    					@endforeach
                        <div class="mx-auto">
                        {{$questions->links()}}
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content') 
<div class="container">
    <div class="row ">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                <div class="card-title">
                	<div class="d-flex align-item-center">
                		<h2>{{$question->title}}</h2>
                		<div class="ml-auto">
                			<a href="{{route('questions.index')}}" class="ml-3 btn btn-outline-secondary">Back to Questions</a>
                		</div>
                	</div>
                </div>
                <hr>
                <div class="media">
                  <!-- @include('shared._vote',[
                       'model'=>$question,
                   ])-->
                    <vote name="question" :model="{{$question}}"></vote> 
                    <div class="media-body leftBorder">
                          {!!$question->body_html!!}
                        <div class="row">
                            <div class="col-md-4">
                                @include('shared._change',[
                                'model'=>$question,
                                'canEdit'=>'update-question',
                                'canDelete'=>'delete-question',
                                ])
                            </div>
                            <div class="col-md-4"></div>
                            <div class="col-md-4 float-right">
                             <user-info :model="{{$question}}" label="Asked"></user-info>
                            </div>
                        </div>
                    </div>                 
                </div>
            </div>
        </div>
    </div>
</div>
<answers :question="{{$question}}"></answers>
</div>
@endsection