routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//$2y$10$slYJhSHKIuo0dMbnSQ8HwOxXa9gpGda69ryHtorvl36/knIu9flwK
/*
Route::get('/',function ()
{
	return Hash::make(111);
});

Route::get('test',function ()
{
	return \Auth::id();
	//view('test');
});

//$2y$10$XUgBekTpGMnEEPhSDeSvZewyfPlfn0Oeq7NQk6joVkUv1iY1XiDm.
*/
Route::get('/','QuestionsController@index');

Auth::routes();

Route::get('/home', 'QuestionsController@index')->name('home');

Auth::routes();

Route::get('/home', 'QuestionsController@index')->name('home');

Auth::routes();

Route::resource('questions', 'QuestionsController')->except('show');
Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show');
Route::resource('questions.answers', 'AnswersController')->except(['create','show']);
Route::post('/answers/{answer}/accept','AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favorite','FavoriteQuestionController@store')->name('answers.favorite');
Route::delete('/questions/{question}/favorite','FavoriteQuestionController@destroy')->name('answers.unfavorite');

Route::post('/questions/{question}/vote','VoteQuestionController');
Route::post('/answers/{answer}/vote','VoteAnswerController');

app/Answer.php
<?php

namespace App;
use App\User;
use App\Question;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use Votabletrait, BodyTrait;
    protected $fillable=['body','user_id'];

    protected $appends=['created_date','body_html','is_best'];

    public function question()
    {
    	return $this->belongsTo(Question::class);
    }

    public function user()
    {
    	return $this->belongsTo(User::class);
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getBodyHtmlAttribute()
    {
        return  parsedown($this->body);
    }
    protected static function boot()
    {
        parent::boot();

        static::created(function($answer)
        {
            $answer->question->increment('answers_count');
        });

        static::deleted(function($answer)
        {
            $question=$answer->question;
            $question->decrement('answers_count');
            if($question->best_answer_id==$answer->id){
                $question->best_answer_id=null;
                $question->save();
            }
        });
    }

    public function getStatusAttribute()
    {
        return $this->isBest() ?"accept":"";
    }

    public function getIsBestAttribute()
    {
        return $this->isBest();
    }

    public function isBest()
    {
       return $this->id==$this->question->best_answer_id;
    }

     public function getIsvoteAttribute()
    {
       return $this->isvote();
    }
  
}

resources/views/shared/_accept.blade.php
@can('accept',$model)
  <a title="This {{$name}} is accepted"
    class="{{\Auth::guest()?'':'move'.' '.$model->status}} "
    onclick="event.preventDefault();document.getElementById('accepte-answer-{{$model->id}}').submit();"
  >
    <i class="fas fa-check fa-2x"></i>
  </a>
  <form method="POST" id="accepte-answer-{{$model->id}}" action="{{route('answers.accept',$model->id)}}" style="display:none;">
    @csrf
  </form>
    @else
@if($model->isBest)
    <a title="This answer is accepted"
     class="{{$model->status}}" 
    >
      <i class="fas fa-check fa-2x"></i>
    </a>
@endif
@endcan

resources/views/shared/_author.blade.php
<span class="text-muted">
    {{$label .' '. $model->created_date}}
</span>
<div class="media mt-2">
    <a href="{{$model->user->url}}">
        <img src="{{$model->user->avatar}}">
    </a>
    <div class="media-body ml-2">
        <a class="mt-1" href="{{$model->user->url}}">
            {{$model->user->name}}
        </a>
    </div>
</div>

resources/views/shared/_change.blade.php
@can($canEdit,$model)
        <a href="{{route('questions.edit',$model)}}" class="btn btn-sm btn-outline-primary">Edit</a>
@endcan
@can($canDelete,$model)
    <form action="{{route('questions.destroy',$model->id)}}" method="post" class="formDelete">
	    @method('Delete')
	    @csrf
	    <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are You Sure?')">
	        Delete
	    </button>
    </form>
@endcan

resources/views/shared/_favorite.blade.php
<a title="Favorite This {{$name}} or not" 
     class="{{\Auth::guest()?'off':'move '.($model->is_favorited?'favorite':'unfavorite')}}"
     onclick="event.preventDefault();document.getElementById('favorite-{{$name}}-{{$model->id}}').submit();" >
  <i class="fas fa-star fa-2x"></i>
  <span class="favorite-count">
    {{$model->favorutes_count}}
  </span>
</a>
<form id="favorite-question-{{$model->id}}" style="display: none;" method="POST" action="/{{$urlSegement}}/{{$model->id}}/favorite">
  @csrf
  @if($model->is_favorited)
    @method('DELETE')
  @endif
</form>

resources/views/shared/_vote.blade.php
@if($model instanceof App\Question)
  @php
     $name='question';
     $urlSegement='questions';
  @endphp
@elseif($model instanceof App\Answer)
  @php
    $name='answer';
    $urlSegement='answers';
  @endphp
@endif

 <div class="d-flex flex-column voteControl">
  <a title="This {{$name}} is useful"
     class="{{\Auth::guest()?'off':'move '. $model->isvote(1)}}"
     onclick="event.preventDefault();document.getElementById('vote-up-{{$name}}-{{$model->id}}').submit();" >
    <i class="fas fa-caret-up fa-3x"></i>
  </a>
  <form id="vote-up-{{$name}}-{{$model->id}}" style="display: none;" method="POST" action="/{{$urlSegement}}/{{$model->id}}/vote">
    @csrf
    <input type="hidden" name="vote" value="1">
  </form>
  <span class="{{\Auth::guest()?'off':'move '.'vote-count'}}">
    {{$model->votes_count}}
  </span>
  <a title="This {{$name}} is unuseful" 
      class="{{\Auth::guest()?'off':'move '.$model->isvote(-1)}}"
      onclick="event.preventDefault();document.getElementById('vote-down-{{$name}}-{{$model->id}}').submit();" >
    <i class="fas fa-caret-down fa-3x"></i>
  </a>
  <form id="vote-down-{{$name}}-{{$model->id}}" style="display: none;" method="POST" action="/{{$urlSegement}}/{{$model->id}}/vote">
    @csrf
    <input type="hidden" name="vote" value="-1">
  </form>
@if($model instanceof App\Question)
    <favorite :question="{{$model}}"></favorite>
@elseif($model instanceof App\Answer)
    <accept :answer="{{$model}}"></accept>
@endif
</div>